<a href="https://colab.research.google.com/github/ananyakaligal/DeepLearning-Assignments/blob/main/Activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math

In [2]:
def basic_sigmoid(x):
    s = 1/(1+math.exp(-x))
    return s

x=basic_sigmoid(-1)
x

0.2689414213699951

In [6]:
#Example of vector operation

import numpy as np

x=np.array([1,2,3])
print(np.exp(x))
print(x+3)


[ 2.71828183  7.3890561  20.08553692]
[4 5 6]


In [5]:
def normaliseRow(x):
    return x / np.linalg.norm(x, axis=1, keepdims=True)

x = np.array([[0, 1000, 4], [2, 6, 4]])
print(normaliseRow(x))

[[0.         0.999992   0.00399997]
 [0.26726124 0.80178373 0.53452248]]


In [7]:

#GRADED FUNCTION: sigmoid

import numpy as np

def sigmoid(x):
  s=1/(1+np.exp(-x))
  return s

x=np.array([1,2,3])
y=sigmoid(x)
y

array([0.73105858, 0.88079708, 0.95257413])

In [8]:

def sigmoid_derivative(y):
  return y*(1-y)

sigmoid_derivative(y)

array([0.19661193, 0.10499359, 0.04517666])

In [9]:
#Graded function : image2vector

def image2vector(image):
  length,height,depth=image.shape
  return image.reshape(length*height*depth,1)

image2vector(np.array([[[0.67826139,0.29380381],[.90714982,0.52835647],[0.4515251,.45097551]],[[0.645826139,0.78380381],[.67714982,0.12835647],[0.26615251,.55017551]],[[0.5826139,0.2953380381],[.90714982,0.52835647],[0.4215251,.45017551]]]))


array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4515251 ],
       [0.45097551],
       [0.64582614],
       [0.78380381],
       [0.67714982],
       [0.12835647],
       [0.26615251],
       [0.55017551],
       [0.5826139 ],
       [0.29533804],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551]])

In [10]:
def normaliseRow(x):
    return x / np.linalg.norm(x, axis=1, keepdims=True)

x = np.array([[0, 1000, 4], [2, 6, 4]])
print(normaliseRow(x))

[[0.         0.999992   0.00399997]
 [0.26726124 0.80178373 0.53452248]]


In [11]:
def softmax(x):
    return np.exp(x) / np.sum(x, axis=1, keepdims=True)

x = np.array([[9, 2, 5, 0, 0], [7, 5, 0, 0, 0]])
print(softmax(x))

[[5.06442745e+02 4.61816006e-01 9.27582244e+00 6.25000000e-02
  6.25000000e-02]
 [9.13860965e+01 1.23677633e+01 8.33333333e-02 8.33333333e-02
  8.33333333e-02]]


In [13]:
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

st = time.process_time()
dot = 0

for i in range(len(x1)):
    dot += x1[i]*x2[i]

sp = time.process_time()

print(f"Time took : {sp-st}")


st = time.process_time()
dot = np.dot(x1, x2)
sp = time.process_time()

print(f"Time took : {sp-st}")


Time took : 0.00011049799999973686
Time took : 0.0002642230000002854
